myapp:
  build: .
  dockerfile: Dockerfile
  command: node_modules/.bin/nodemon index.js    
  environment:
   NODE_ENV: development  
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/myapp
    - /home/app/myapp/node_modules 
